{% set name = "jsondiff" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34941bc431d10aa15828afe1cbb644977a114e75eef6cc74fb58951312326303

build:
  number: 1
  noarch: python
  entry_points:
    - jdiff=jsondiff.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - jsondiff
  commands:
    - jdiff --help

about:
  home: https://github.com/ZoomerAnalytics/jsondiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Diff JSON and JSON-like structures in Python

extra:
  recipe-maintainers:
    - mariusvniekerk
