{% set name = "jsondiff" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2795844ef075ec8a2b8d385c4d59f5ea48b08e7180fce3cb2787be0db00b1fb4

build:
  number: 0
  entry_points:
    - jdiff=jsondiff.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

# No test_jsondiff.py file found in tests for version 2.0.0
test:
  imports:
    - jsondiff
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - jdiff --help
  requires:
    - pip

about:
  home: https://github.com/xlwings/jsondiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Diff JSON and JSON-like structures in Python.
  description: Diff JSON and JSON-like structures in Python.
  doc_url: https://github.com/xlwings/jsondiff/blob/master/README.md
  dev_url: https://github.com/xlwings/jsondiff

extra:
  recipe-maintainers:
    - mariusvniekerk