travis:
  secure:
    BINSTAR_TOKEN: DKz1T5Q4QRRQp5AbLsKVob/oI5metbOS3VbBrEQo0mG/AjXosfcmXzHVgSEmJsmWoGZEXQ7QFeQDd/UZB9QGxuwxpnc7NfTmu5vTWqMH+E4SImqbm0aGCDa0q+J7DK3vBzC244vaf1gJmzLIavA59yfdVPKSS9ZdnMRjYBeUPTmrjOdUUrGy44RjfdrTDh2FnkrG5Z+vWgOyS/BMdiTCz5R+N75EmmaTRZ5cs9y9k1+GV0RRgWS66ZrCD+92dM9W/G8L8C8PDeii3vKvIrccQ2fplFfNAPulme52xeLJVR+mdsEzOsLOGrTuabxk0qNr1R3/mHf3zhtlX3KSIa3HM4qlVqXPMRcBd8jR9RuUdxwsamj8JWTLE3QsUWvCjlFjPwc3MxjBJYu020ydfxO7Gr0T+UVwZFuWrBmeKzWGud/OsrslX5S2mZx3Dx0MuzscerusvGIVGqy5Fzhz9WnIHeBcHnguyYQbSNmMRcAhZyj/8FbKgi5HrLRUa9zyImcpmFH7hg5ZpbfEy8dCQVwM2L59qv+vwaRRQHpYoFyln6d4Ez61H5Z6CV3bzcYSb3nnekewtrmijmL+SmirKclI6+bt5UI6KzwYYUNLfxls0T3ZwN2mnX94+xCv/+I9Q8dnIiuWiLQMqM2IPo+5XZ5cSsbfLAp5K6U3CKKZ8bJb8+A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
